services:
  #Database
  db:
    image: mysql:5.7
    platform: linux/amd64  # Use amd64 platform
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite

  #phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64  # Use amd64 platform
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wpsite
  #Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    platform: linux/amd64  # Use amd64 platform
    ports:
      - "8000:80"
    restart: always
    environment:
      # Default port for mysql
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - "./:/var/www/html"
    networks:
      - wpsite

networks:
  wpsite:
volumes:
  db_data:
